import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useSelector } from 'react-redux'
import ThemeDropdown from '@/components/Dropdown/Theme'
import TypeWriter from '@/components/TypeWriter'
import WebDropdown from '../Dropdown/Web'
import Web2Introduction from '../Introduction'
import Web2Header from '../Header/Web2Header'
import AnimatedCursor from 'react-animated-cursor'

const WEB2 = () => {
  const theme = useSelector((state: any) => state.theme)
  const data = 'Anish*Ali'
  return (
    <div className={theme}>
      <Web2Header />
      <div className="bg-background">
        <Head>
          <title>Anish Ali</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="flex justify-center items-center mt-12">
          {data.split('').map((v) => {
            const random = Math.random() * 3
            const r = Number(random.toFixed(0))
            return (
              <p key={v} className={`char${r + 1} text-primary text-7xl`}>
                {v == '*' ? <span className="ml-5"> </span> : v}
              </p>
            )
          })}
        </div>
        <div className="flex justify-center text-primary text-3xl md:text-4xl lg:text-6xl items-center mt-4">
          I'm<span className="w-2"></span> <TypeWriter />
        </div>
      </div>
      <Web2Introduction />
      <footer className={styles.footer}>
        <div className="space-x-7 flex">
          <div className="w-fit">
            <ThemeDropdown />
          </div>
          <div className=" w-fit">
            <WebDropdown />
          </div>
        </div>
      </footer>
      <AnimatedCursor
        color={theme == 'dark' ? '255,255,255' : '0,0,0'}
        innerSize={8}
        outerSize={35}
        innerScale={1}
        outerScale={1.7}
        outerAlpha={0}
        outerStyle={{
          border: `3px solid ${theme == 'dark' ? '#fff' : '#000'}`
        }}
      />
    </div>
  )
}

export default WEB2
