import Head from 'next/head'
import React from 'react'
import { useSelector } from 'react-redux'
import Header from '../Header/Web3Header'

const WEB3 = () => {
  const theme = useSelector((state: any) => state.theme)
  return (
    <div className={theme}>
      <Head>
        <title>Anish Ali</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-background h-screen w-screen">
        <header>
          <Header />
        </header>
      </div>
    </div>
  )
}

export default WEB3
